mainSections:
  - posts

description: Tech ramblings

dateFormat:

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme:

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/icon.png
publisherName: theboring.dev
publisherLogo: images/icon.png

highlight:
  handler: highlightjs

  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/master/build/languages for available languages.
    languages:
      - javascript
    # See https://github.com/highlightjs/cdn-release/tree/master/build/styles for available styles.
    style: solarized-light

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

diagram:
  handler: mermaid

  # mermaid:
  #   # Browse https://mermaid-js.github.io/mermaid/#/Setup to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `diagramPadding` should be written as `diagram-Padding` or other acceptable formats.
  #   theme:
  #   flowchart:
  #     diagram-padding:
